version: '3.8'
  services:
    postgres:
      image: postgres:15
      environment:
        POSTGRES_DB: aicareerguidance
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: your_postgres_password
      ports:
        - "5432:5432"
    redis:
      image: redis:7
      ports:
        - "6379:6379"